import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { WalletConnectionProvider } from "@/providers/WalletProvider";
import "./globals.css";
import { ConnectWallet } from "@/components/ui/ConnectWallet";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <WalletConnectionProvider>
          <ConnectWallet />
          {children}
        </WalletConnectionProvider>
      </body>
    </html>
  );
}
